// 500 words sorted by length (3–12+ letters)
// Distribution: 3-letter(40), 4(60), 5(80), 6(80), 7(70), 8(60), 9(50), 10(30), 11(20), 12+(10)
export const WORD_LIST = [
  // === 3-letter words (40) ===
  { word: 'SUN', meaning: 'The star at the center of our solar system' },
  { word: 'BIG', meaning: 'Large in size, amount, or degree' },
  { word: 'RUN', meaning: 'To move quickly using your legs' },
  { word: 'CAT', meaning: 'A small furry animal often kept as a pet' },
  { word: 'MAP', meaning: 'A drawing that shows where places are' },
  { word: 'HOP', meaning: 'To jump on one foot or make short jumps' },
  { word: 'CUP', meaning: 'A small container used for drinking' },
  { word: 'RED', meaning: 'The color of fire trucks and ripe tomatoes' },
  { word: 'DOG', meaning: 'A friendly animal that barks' },
  { word: 'FIN', meaning: 'The flat part on a fish that helps it swim' },
  { word: 'OWL', meaning: 'A bird that hunts at night with large eyes' },
  { word: 'JAM', meaning: 'A sweet spread made from fruit' },
  { word: 'FOX', meaning: 'A clever wild animal with a bushy tail' },
  { word: 'HEN', meaning: 'A female chicken' },
  { word: 'ICE', meaning: 'Frozen water' },
  { word: 'JOY', meaning: 'A feeling of great happiness' },
  { word: 'KEY', meaning: 'A tool used to open a lock' },
  { word: 'LOG', meaning: 'A thick piece of cut wood' },
  { word: 'MUD', meaning: 'Wet soft earth' },
  { word: 'NUT', meaning: 'A hard-shelled fruit with a seed inside' },
  { word: 'PIG', meaning: 'A pink farm animal with a curly tail' },
  { word: 'RAG', meaning: 'A piece of old worn cloth' },
  { word: 'SAP', meaning: 'The fluid that flows through plants' },
  { word: 'TAR', meaning: 'A thick dark sticky liquid used on roads' },
  { word: 'URN', meaning: 'A tall rounded vase' },
  { word: 'VAN', meaning: 'A large covered vehicle for carrying goods' },
  { word: 'WAX', meaning: 'A solid substance that melts when heated' },
  { word: 'YAM', meaning: 'A starchy root vegetable' },
  { word: 'ZAP', meaning: 'To destroy or strike suddenly' },
  { word: 'BOW', meaning: 'A curved weapon for shooting arrows' },
  { word: 'DEW', meaning: 'Tiny drops of water that form overnight' },
  { word: 'ELF', meaning: 'A small magical creature from stories' },
  { word: 'GEM', meaning: 'A precious stone' },
  { word: 'HUB', meaning: 'The center of a wheel or activity' },
  { word: 'INK', meaning: 'A colored fluid used for writing' },
  { word: 'JAW', meaning: 'The bony structure of the mouth' },
  { word: 'KIT', meaning: 'A set of tools or equipment' },
  { word: 'LAP', meaning: 'One complete trip around a track' },
  { word: 'OAK', meaning: 'A large tree that produces acorns' },
  { word: 'PEA', meaning: 'A small round green vegetable' },

  // === 4-letter words (60) ===
  { word: 'STAR', meaning: 'A bright point of light in the night sky' },
  { word: 'MOON', meaning: 'The natural satellite that orbits Earth' },
  { word: 'FROG', meaning: 'A small jumping amphibian' },
  { word: 'SHIP', meaning: 'A large vessel for traveling on water' },
  { word: 'BIRD', meaning: 'An animal with feathers and wings' },
  { word: 'FISH', meaning: 'An animal that lives and breathes in water' },
  { word: 'TREE', meaning: 'A tall plant with a wooden trunk' },
  { word: 'LAKE', meaning: 'A large body of water surrounded by land' },
  { word: 'CAVE', meaning: 'A natural underground hollow space' },
  { word: 'RAIN', meaning: 'Water drops falling from clouds' },
  { word: 'WIND', meaning: 'Moving air' },
  { word: 'SAND', meaning: 'Tiny grains found on beaches and deserts' },
  { word: 'GOLD', meaning: 'A precious yellow metal' },
  { word: 'BONE', meaning: 'The hard parts inside your body' },
  { word: 'SEED', meaning: 'The part of a plant that grows into a new one' },
  { word: 'LEAF', meaning: 'A flat green part of a plant' },
  { word: 'NEST', meaning: 'A home built by birds' },
  { word: 'WOLF', meaning: 'A wild animal related to dogs' },
  { word: 'HIVE', meaning: 'A home for bees' },
  { word: 'FOAM', meaning: 'A mass of small bubbles' },
  { word: 'GLOW', meaning: 'To give off a soft steady light' },
  { word: 'HAZE', meaning: 'A slight mist or smoke in the air' },
  { word: 'KITE', meaning: 'A toy flown in the wind on a string' },
  { word: 'MIST', meaning: 'Thin fog near the ground' },
  { word: 'PEAK', meaning: 'The pointed top of a mountain' },
  { word: 'REEF', meaning: 'A ridge of rock or coral near the surface of water' },
  { word: 'TIDE', meaning: 'The rise and fall of ocean water' },
  { word: 'VINE', meaning: 'A climbing or trailing plant' },
  { word: 'ECHO', meaning: 'A reflected sound heard again' },
  { word: 'ARCH', meaning: 'A curved structure over an opening' },
  { word: 'BARN', meaning: 'A large farm building for storing crops or housing animals' },
  { word: 'COAL', meaning: 'A black rock burned as fuel' },
  { word: 'DUSK', meaning: 'The time just before night when the sky grows dark' },
  { word: 'FERN', meaning: 'A green plant with feathery leaves' },
  { word: 'GULF', meaning: 'A large area of sea partly enclosed by land' },
  { word: 'HELM', meaning: 'A wheel or lever for steering a ship' },
  { word: 'ISLE', meaning: 'A small island' },
  { word: 'JADE', meaning: 'A green gemstone' },
  { word: 'LAVA', meaning: 'Hot melted rock from a volcano' },
  { word: 'MAZE', meaning: 'A complex network of paths to find your way through' },
  { word: 'OPAL', meaning: 'A gemstone that shows many colors' },
  { word: 'PYRE', meaning: 'A pile of wood for burning a body' },
  { word: 'RUST', meaning: 'A reddish coating that forms on iron when wet' },
  { word: 'SLAB', meaning: 'A thick flat piece of stone or concrete' },
  { word: 'TUSK', meaning: 'A long pointed tooth that sticks out of an animal\'s mouth' },
  { word: 'WREN', meaning: 'A very small brown bird' },
  { word: 'YOKE', meaning: 'A wooden beam used to join two animals together' },
  { word: 'ZINC', meaning: 'A bluish-white metal used for coating' },
  { word: 'APEX', meaning: 'The highest point or top of something' },
  { word: 'DUNE', meaning: 'A mound of sand formed by the wind' },

  // === 5-letter words (80) ===
  { word: 'BRAVE', meaning: 'Ready to face danger without fear' },
  { word: 'CLIMB', meaning: 'To go up using your hands and feet' },
  { word: 'FLOAT', meaning: 'To stay on the surface of a liquid' },
  { word: 'PROUD', meaning: 'Feeling happy about an achievement' },
  { word: 'SHINY', meaning: 'Bright and reflecting light' },
  { word: 'STORM', meaning: 'Very bad weather with strong winds and rain' },
  { word: 'GRASP', meaning: 'To take hold of something firmly' },
  { word: 'BLOOM', meaning: 'When a flower opens up its petals' },
  { word: 'CREEK', meaning: 'A small narrow stream of water' },
  { word: 'SWIFT', meaning: 'Moving or able to move very quickly' },
  { word: 'ORBIT', meaning: 'The curved path a planet follows around a star' },
  { word: 'LUNAR', meaning: 'Relating to the moon' },
  { word: 'COMET', meaning: 'A bright object in space with a long tail' },
  { word: 'QUEST', meaning: 'A long search for something important' },
  { word: 'SOLAR', meaning: 'Relating to the sun' },
  { word: 'FROST', meaning: 'A thin layer of ice on cold surfaces' },
  { word: 'BLAZE', meaning: 'A large strong fire that burns brightly' },
  { word: 'GLOBE', meaning: 'A round model of the Earth' },
  { word: 'CRANE', meaning: 'A large machine for lifting or a tall bird' },
  { word: 'FLAME', meaning: 'A glowing stream of burning gas' },
  { word: 'OCEAN', meaning: 'A vast body of salt water covering most of Earth' },
  { word: 'DELTA', meaning: 'A triangular area where a river meets the sea' },
  { word: 'RIDGE', meaning: 'A long narrow raised area of land' },
  { word: 'CORAL', meaning: 'Hard material formed by tiny sea creatures' },
  { word: 'FJORD', meaning: 'A long narrow inlet of sea between cliffs' },
  { word: 'MARSH', meaning: 'An area of soft wet land' },
  { word: 'LEDGE', meaning: 'A narrow flat surface sticking out from a wall or cliff' },
  { word: 'CEDAR', meaning: 'A large evergreen tree with sweet-smelling wood' },
  { word: 'MAPLE', meaning: 'A tree known for its syrup and leaf shape' },
  { word: 'BIRCH', meaning: 'A tree with thin peeling bark' },
  { word: 'IVORY', meaning: 'A hard white substance from tusks' },
  { word: 'AMBER', meaning: 'A yellowish fossilized tree resin' },
  { word: 'PEARL', meaning: 'A smooth round gem formed inside an oyster' },
  { word: 'FORGE', meaning: 'A place where metal is heated and shaped' },
  { word: 'REIGN', meaning: 'The period when a king or queen rules' },
  { word: 'SIEGE', meaning: 'Surrounding a place to force surrender' },
  { word: 'TRUCE', meaning: 'An agreement to stop fighting temporarily' },
  { word: 'VAULT', meaning: 'A secure room for storing valuables' },
  { word: 'PRISM', meaning: 'A glass shape that splits light into colors' },
  { word: 'NERVE', meaning: 'A fiber that carries signals between brain and body' },
  { word: 'SPINE', meaning: 'The column of bones down the center of the back' },
  { word: 'FIBER', meaning: 'A thin thread of natural or artificial material' },
  { word: 'TOXIN', meaning: 'A poisonous substance produced by living things' },
  { word: 'LARVA', meaning: 'The young form of an insect before it changes shape' },
  { word: 'SPORE', meaning: 'A tiny cell that can grow into a new organism' },
  { word: 'GLYPH', meaning: 'A carved or inscribed symbol' },
  { word: 'CIPHER', meaning: 'A secret code for writing messages' },
  { word: 'RELIC', meaning: 'An object surviving from the distant past' },
  { word: 'ABYSS', meaning: 'A deep bottomless space' },
  { word: 'OASIS', meaning: 'A green fertile area in a desert' },
  { word: 'THAW', meaning: 'To become unfrozen' },
  { word: 'PLUME', meaning: 'A large feather or column of smoke' },
  { word: 'HAVEN', meaning: 'A safe place or shelter' },
  { word: 'TUNIC', meaning: 'A loose-fitting garment reaching the knees' },
  { word: 'LANCE', meaning: 'A long weapon carried by knights on horseback' },
  { word: 'WRATH', meaning: 'Extreme anger' },
  { word: 'GUISE', meaning: 'An outward appearance that hides the truth' },
  { word: 'KNACK', meaning: 'A natural skill or talent' },
  { word: 'DWARF', meaning: 'A very small person or creature from myths' },
  { word: 'CRUST', meaning: 'The hard outer layer of bread or Earth' },
  { word: 'PIXEL', meaning: 'A tiny dot that makes up a digital image' },
  { word: 'RADAR', meaning: 'A system for detecting objects using radio waves' },
  { word: 'VIRUS', meaning: 'A tiny agent that causes disease' },
  { word: 'ROBOT', meaning: 'A machine that can carry out tasks automatically' },
  { word: 'LASER', meaning: 'A device that produces an intense beam of light' },
  { word: 'ALLOY', meaning: 'A metal made by mixing two or more metals' },
  { word: 'MAGMA', meaning: 'Hot liquid rock beneath Earth\'s surface' },
  { word: 'QUAKE', meaning: 'A sudden shaking of the ground' },
  { word: 'VAPOR', meaning: 'A substance in gas form, like steam' },
  { word: 'IONIC', meaning: 'Related to atoms that have gained or lost electrons' },
  { word: 'FLORA', meaning: 'The plants of a particular region' },
  { word: 'FAUNA', meaning: 'The animals of a particular region' },
  { word: 'BIOME', meaning: 'A large area with similar climate and living things' },
  { word: 'EPOCH', meaning: 'A long and distinct period of history' },
  { word: 'ULTRA', meaning: 'Going beyond what is normal or usual' },
  { word: 'TEMPO', meaning: 'The speed at which music is played' },
  { word: 'MURAL', meaning: 'A large painting done on a wall' },
  { word: 'VOWEL', meaning: 'A speech sound like A, E, I, O, or U' },
  { word: 'QUOTA', meaning: 'A limited number or amount allowed' },
  { word: 'SONIC', meaning: 'Relating to sound or its speed' },

  // === 6-letter words (80) ===
  { word: 'GALAXY', meaning: 'A system of millions of stars held together by gravity' },
  { word: 'FROZEN', meaning: 'Turned into ice or very cold' },
  { word: 'JUNGLE', meaning: 'A dense tropical forest' },
  { word: 'SHIELD', meaning: 'A protective barrier' },
  { word: 'BREEZE', meaning: 'A gentle wind' },
  { word: 'KNIGHT', meaning: 'A medieval warrior who served a lord' },
  { word: 'CASTLE', meaning: 'A large fortified building from medieval times' },
  { word: 'PIRATE', meaning: 'A person who robs ships at sea' },
  { word: 'DRAGON', meaning: 'A mythical fire-breathing creature' },
  { word: 'TEMPLE', meaning: 'A building for worship' },
  { word: 'CANYON', meaning: 'A deep narrow valley with steep sides' },
  { word: 'ISLAND', meaning: 'A piece of land surrounded by water' },
  { word: 'DESERT', meaning: 'A dry area with very little rainfall' },
  { word: 'FOREST', meaning: 'A large area covered with trees' },
  { word: 'TUNDRA', meaning: 'A vast flat treeless arctic region' },
  { word: 'GEYSER', meaning: 'A hot spring that erupts water into the air' },
  { word: 'QUARTZ', meaning: 'A hard mineral found in many rocks' },
  { word: 'FOSSIL', meaning: 'Preserved remains of ancient living things' },
  { word: 'HARBOR', meaning: 'A sheltered area of water where ships dock' },
  { word: 'BEACON', meaning: 'A light or signal that guides' },
  { word: 'FALCON', meaning: 'A fast bird of prey' },
  { word: 'PYTHON', meaning: 'A large snake that squeezes its prey' },
  { word: 'WALRUS', meaning: 'A large marine mammal with tusks' },
  { word: 'SCARAB', meaning: 'A type of beetle sacred in ancient Egypt' },
  { word: 'BRONZE', meaning: 'A metal made from copper and tin' },
  { word: 'COBALT', meaning: 'A hard silvery-blue metal' },
  { word: 'MOSAIC', meaning: 'A picture made from small colored pieces' },
  { word: 'FATHOM', meaning: 'A unit of water depth equal to six feet' },
  { word: 'SUMMIT', meaning: 'The highest point of a mountain' },
  { word: 'MAGNET', meaning: 'An object that attracts iron' },
  { word: 'PRIMAL', meaning: 'Relating to the earliest age of history' },
  { word: 'SPIRIT', meaning: 'The non-physical part of a person, the soul' },
  { word: 'WISDOM', meaning: 'The quality of having experience and good judgment' },
  { word: 'LEGEND', meaning: 'A famous story from the past' },
  { word: 'TROPHY', meaning: 'A prize awarded for winning' },
  { word: 'VOYAGE', meaning: 'A long journey by sea or through space' },
  { word: 'ZENITH', meaning: 'The highest point reached' },
  { word: 'NEBULA', meaning: 'A cloud of gas and dust in space' },
  { word: 'PHOTON', meaning: 'A tiny particle of light' },
  { word: 'PROTON', meaning: 'A positively charged particle in an atom' },
  { word: 'CARBON', meaning: 'An element found in all living things' },
  { word: 'PLASMA', meaning: 'The fourth state of matter, an ionized gas' },
  { word: 'ENZYME', meaning: 'A protein that speeds up chemical reactions in the body' },
  { word: 'GENOME', meaning: 'The complete set of genes in an organism' },
  { word: 'POLLEN', meaning: 'Fine powder from flowers that helps plants reproduce' },
  { word: 'LICHEN', meaning: 'A plant-like organism growing on rocks and trees' },
  { word: 'TRENCH', meaning: 'A long deep ditch' },
  { word: 'STEPPE', meaning: 'A large flat grassland in Europe or Asia' },
  { word: 'RAVINE', meaning: 'A deep narrow gorge' },
  { word: 'METEOR', meaning: 'A streak of light from space debris burning up' },
  { word: 'LAUNCH', meaning: 'To send something into the air or space' },
  { word: 'CIPHER', meaning: 'A secret code or zero' },
  { word: 'SCROLL', meaning: 'A roll of paper with writing on it' },
  { word: 'GOBLET', meaning: 'A drinking cup with a stem and base' },
  { word: 'RIDDLE', meaning: 'A clever question asked as a puzzle' },
  { word: 'NIMBLE', meaning: 'Quick and light in movement' },
  { word: 'THRIVE', meaning: 'To grow and develop well' },
  { word: 'HERALD', meaning: 'A person who announces important news' },
  { word: 'PLEDGE', meaning: 'A serious promise or agreement' },
  { word: 'VIRTUE', meaning: 'A quality considered morally good' },
  { word: 'MATRIX', meaning: 'A grid of numbers or an environment where something develops' },
  { word: 'BONFIRE', meaning: 'A large outdoor fire' },
  { word: 'FOSSIL', meaning: 'The preserved remains of ancient living things' },
  { word: 'AURORA', meaning: 'A natural light display in the sky near the poles' },
  { word: 'CANOPY', meaning: 'The uppermost layer of branches in a forest' },
  { word: 'DAGGER', meaning: 'A short pointed knife used as a weapon' },
  { word: 'FAMINE', meaning: 'Extreme shortage of food in a region' },
  { word: 'GALAXY', meaning: 'A huge system of stars held together by gravity' },
  { word: 'JACKAL', meaning: 'A wild animal related to dogs found in Africa' },
  { word: 'LAGOON', meaning: 'A shallow body of water separated from the sea' },
  { word: 'MARROW', meaning: 'Soft tissue inside bones' },
  { word: 'OSPREY', meaning: 'A large fish-eating bird of prey' },
  { word: 'PARCEL', meaning: 'A package wrapped for sending' },
  { word: 'SIPHON', meaning: 'A tube for moving liquid from one container to another' },
  { word: 'TURRET', meaning: 'A small tower on top of a building or vehicle' },
  { word: 'VORTEX', meaning: 'A spinning mass of air or water' },
  { word: 'WRAITH', meaning: 'A ghostly figure' },
  { word: 'TETHER', meaning: 'A rope or chain used to tie something' },
  { word: 'RUBBLE', meaning: 'Broken pieces of brick or stone' },
  { word: 'QUIVER', meaning: 'A case for holding arrows or to shake slightly' },

  // === 7-letter words (70) ===
  { word: 'GRAVITY', meaning: 'The force that pulls objects toward each other' },
  { word: 'ANCIENT', meaning: 'Belonging to a time long ago' },
  { word: 'JOURNEY', meaning: 'A long trip from one place to another' },
  { word: 'IMAGINE', meaning: 'To create pictures or ideas in your mind' },
  { word: 'MYSTERY', meaning: 'Something difficult to understand or explain' },
  { word: 'BALANCE', meaning: 'Being steady and not falling to one side' },
  { word: 'HARVEST', meaning: 'The time when crops are gathered' },
  { word: 'COURAGE', meaning: 'The ability to do something that frightens you' },
  { word: 'COMPETE', meaning: 'To try to win or do better than others' },
  { word: 'SHELTER', meaning: 'A place that protects from weather or danger' },
  { word: 'ECLIPSE', meaning: 'When one space object blocks light from another' },
  { word: 'PYRAMID', meaning: 'A structure with triangular sides meeting at a point' },
  { word: 'GLACIER', meaning: 'A huge slow-moving mass of ice' },
  { word: 'VOLCANO', meaning: 'A mountain that can erupt with lava' },
  { word: 'TORNADO', meaning: 'A violent rotating column of air' },
  { word: 'MONSOON', meaning: 'A seasonal wind bringing heavy rain' },
  { word: 'COMPASS', meaning: 'A device for finding direction' },
  { word: 'CRYSTAL', meaning: 'A solid with atoms arranged in a pattern' },
  { word: 'MAMMOTH', meaning: 'A large extinct elephant-like animal' },
  { word: 'PANTHER', meaning: 'A large wild cat, usually black' },
  { word: 'PHOENIX', meaning: 'A mythical bird reborn from fire' },
  { word: 'UNICORN', meaning: 'A mythical horse with a single horn' },
  { word: 'CHIMERA', meaning: 'A mythical creature made of different animals' },
  { word: 'ALCHEMY', meaning: 'An ancient practice aiming to turn metals into gold' },
  { word: 'CITADEL', meaning: 'A fortress overlooking a city' },
  { word: 'RAMPART', meaning: 'A defensive wall around a fort' },
  { word: 'BASTION', meaning: 'A stronghold or fortified place' },
  { word: 'DYNASTY', meaning: 'A line of rulers from the same family' },
  { word: 'MONARCH', meaning: 'A king or queen' },
  { word: 'EMPEROR', meaning: 'The ruler of an empire' },
  { word: 'NOMADIC', meaning: 'Moving from place to place with no fixed home' },
  { word: 'ALGEBRA', meaning: 'A branch of math using symbols and letters' },
  { word: 'ELEMENT', meaning: 'A basic substance that cannot be broken down further' },
  { word: 'ISOTOPE', meaning: 'A variant of an element with different neutrons' },
  { word: 'NEUTRON', meaning: 'A particle in an atom with no electric charge' },
  { word: 'REACTOR', meaning: 'A device where nuclear reactions happen' },
  { word: 'CURRENT', meaning: 'A flow of water, air, or electricity' },
  { word: 'TURBINE', meaning: 'A machine with blades turned by flowing water or air' },
  { word: 'HABITAT', meaning: 'The natural home of an animal or plant' },
  { word: 'SPECIES', meaning: 'A group of similar living things' },
  { word: 'MICROBE', meaning: 'A tiny living thing too small to see' },
  { word: 'RIPCORD', meaning: 'A cord pulled to open a parachute' },
  { word: 'FURNACE', meaning: 'An enclosed space for producing intense heat' },
  { word: 'CATAPULT', meaning: 'A device for launching objects' },
  { word: 'LABYRINTH', meaning: 'A complex maze' },
  { word: 'TALISMAN', meaning: 'An object believed to have magical powers' },
  { word: 'PARAGON', meaning: 'A model of excellence' },
  { word: 'PARADOX', meaning: 'A statement that contradicts itself but may be true' },
  { word: 'CHIMNEY', meaning: 'A vertical channel that carries smoke from a fire' },
  { word: 'TRINKET', meaning: 'A small ornament or piece of jewelry' },
  { word: 'GRANITE', meaning: 'A very hard type of rock' },
  { word: 'JAVELIN', meaning: 'A light spear thrown in athletic competitions' },
  { word: 'LANTERN', meaning: 'A lamp with a protective case' },
  { word: 'MAMMOTH', meaning: 'A huge extinct relative of the elephant' },
  { word: 'ORGANIC', meaning: 'Relating to living things or chemical compounds with carbon' },
  { word: 'PILGRIM', meaning: 'A person who travels to a sacred place' },
  { word: 'QUARREL', meaning: 'An angry argument or disagreement' },
  { word: 'SAPPHIRE', meaning: 'A precious blue gemstone' },
  { word: 'TEMPEST', meaning: 'A violent and windy storm' },
  { word: 'UNRAVEL', meaning: 'To undo twisted threads or solve a mystery' },
  { word: 'VERDICT', meaning: 'A decision made by a jury in a trial' },
  { word: 'WARRIOR', meaning: 'A brave and experienced fighter' },
  { word: 'ZEPHYR', meaning: 'A soft gentle breeze' },
  { word: 'CRYPTIC', meaning: 'Having a hidden or mysterious meaning' },
  { word: 'EMBARGO', meaning: 'An official ban on trade with a country' },
  { word: 'FLUTTER', meaning: 'To move wings rapidly or wave quickly' },
  { word: 'GADGET', meaning: 'A small mechanical or electronic device' },
  { word: 'HARMONY', meaning: 'A pleasing combination of sounds or elements' },
  { word: 'IMPULSE', meaning: 'A sudden strong urge to act' },
  { word: 'KINETIC', meaning: 'Relating to motion' },

  // === 8-letter words (60) ===
  { word: 'UNIVERSE', meaning: 'All of space and everything in it' },
  { word: 'ASTEROID', meaning: 'A rocky body orbiting the sun' },
  { word: 'DINOSAUR', meaning: 'A prehistoric reptile that ruled the Earth' },
  { word: 'TREASURE', meaning: 'A collection of valuable things' },
  { word: 'MARATHON', meaning: 'A long running race of about 26 miles' },
  { word: 'MAGNETIC', meaning: 'Having the property of attracting iron' },
  { word: 'TROPICAL', meaning: 'Relating to the hot region near the equator' },
  { word: 'DISSOLVE', meaning: 'To become mixed into a liquid' },
  { word: 'SPECTRUM', meaning: 'A band of colors produced by splitting light' },
  { word: 'MOLECULE', meaning: 'A group of atoms bonded together' },
  { word: 'BACTERIA', meaning: 'Tiny single-celled organisms' },
  { word: 'CATALYST', meaning: 'Something that speeds up a chemical reaction' },
  { word: 'SYMMETRY', meaning: 'When two halves of something match perfectly' },
  { word: 'ABSOLUTE', meaning: 'Complete and total, not limited' },
  { word: 'ALLIANCE', meaning: 'A union formed for mutual benefit' },
  { word: 'ANCESTOR', meaning: 'A person from whom one is descended' },
  { word: 'ARTIFACT', meaning: 'An object made by humans, especially of historical interest' },
  { word: 'BOUNDARY', meaning: 'A line that marks the edge of an area' },
  { word: 'CALENDAR', meaning: 'A system for organizing days and months' },
  { word: 'CEREMONY', meaning: 'A formal event held to celebrate something' },
  { word: 'CURRENCY', meaning: 'The money system used in a country' },
  { word: 'DRIFTING', meaning: 'Moving slowly without direction' },
  { word: 'ELOQUENT', meaning: 'Fluent and persuasive in speaking or writing' },
  { word: 'FRICTION', meaning: 'Resistance when surfaces slide against each other' },
  { word: 'GEOMETRY', meaning: 'The branch of math dealing with shapes' },
  { word: 'HYDROGEN', meaning: 'The lightest and most abundant element' },
  { word: 'INFRARED', meaning: 'Light with a wavelength longer than visible red' },
  { word: 'JUDICIAL', meaning: 'Relating to courts and judges' },
  { word: 'KEYSTONE', meaning: 'The central stone in an arch that holds it together' },
  { word: 'LUMINOUS', meaning: 'Giving off light, shining' },
  { word: 'MANIFEST', meaning: 'Clear and obvious to see' },
  { word: 'NAUTICAL', meaning: 'Relating to sailors or navigation' },
  { word: 'OBSIDIAN', meaning: 'A dark volcanic glass' },
  { word: 'PARADIGM', meaning: 'A typical example or pattern of something' },
  { word: 'RESONANT', meaning: 'Deep, clear, and continuing to sound' },
  { word: 'SILICATE', meaning: 'A mineral compound found in most rocks' },
  { word: 'TANGIBLE', meaning: 'Real enough to be touched or felt' },
  { word: 'VELOCITY', meaning: 'The speed of something in a given direction' },
  { word: 'WAYPOINT', meaning: 'A stopping place on a journey' },
  { word: 'YEARNING', meaning: 'A deep longing or desire' },
  { word: 'ZETABYTE', meaning: 'An extremely large unit of digital data' },
  { word: 'BLIZZARD', meaning: 'A severe snowstorm with strong winds' },
  { word: 'CONQUEST', meaning: 'The act of taking control by force' },
  { word: 'DECAYING', meaning: 'Slowly breaking down or rotting' },
  { word: 'ENSEMBLE', meaning: 'A group performing together' },
  { word: 'FALCONER', meaning: 'A person who trains hawks for hunting' },
  { word: 'GUARDIAN', meaning: 'A person who protects or defends' },
  { word: 'HERITAGE', meaning: 'Traditions and values passed down through generations' },
  { word: 'ILLUSION', meaning: 'Something that appears different from reality' },
  { word: 'JUDGMENT', meaning: 'The ability to make good decisions' },
  { word: 'MOMENTUM', meaning: 'The force of a moving object' },
  { word: 'NORTHERN', meaning: 'In or toward the north' },
  { word: 'OPPOSING', meaning: 'Being against or in conflict' },
  { word: 'POSITIVE', meaning: 'Expressing agreement or optimism' },
  { word: 'QUANTITY', meaning: 'An amount or number of something' },
  { word: 'RAINFALL', meaning: 'The amount of rain that falls in an area' },
  { word: 'SKELETON', meaning: 'The framework of bones in a body' },
  { word: 'TITANIUM', meaning: 'A strong lightweight metal' },
  { word: 'VOLATILE', meaning: 'Likely to change quickly and unpredictably' },
  { word: 'WINGSPAN', meaning: 'The distance from tip to tip of wings' },

  // === 9-letter words (50) ===
  { word: 'ATMOSPHERE', meaning: 'The layer of gases surrounding a planet' },
  { word: 'TELESCOPE', meaning: 'An instrument for seeing distant objects in space' },
  { word: 'BRILLIANT', meaning: 'Extremely clever or bright and shining' },
  { word: 'COMMUNITY', meaning: 'A group of people sharing interests or living together' },
  { word: 'DANGEROUS', meaning: 'Able to cause harm or injury' },
  { word: 'ELABORATE', meaning: 'Very detailed and carefully planned' },
  { word: 'FREQUENCY', meaning: 'How often something happens' },
  { word: 'NEGOTIATE', meaning: 'To discuss in order to reach an agreement' },
  { word: 'PENINSULA', meaning: 'Land almost surrounded by water on three sides' },
  { word: 'NARRATIVE', meaning: 'A spoken or written account of events' },
  { word: 'EVOLUTION', meaning: 'The gradual change of species over time' },
  { word: 'SATELLITE', meaning: 'An object orbiting a planet or star' },
  { word: 'HURRICANE', meaning: 'A powerful tropical storm with strong winds' },
  { word: 'AVALANCHE', meaning: 'A mass of snow sliding rapidly down a mountain' },
  { word: 'LABYRINTH', meaning: 'A complicated maze of passages' },
  { word: 'MECHANISM', meaning: 'A system of parts working together' },
  { word: 'STRUCTURE', meaning: 'The way something is built or organized' },
  { word: 'ALGORITHM', meaning: 'A step-by-step process for solving a problem' },
  { word: 'ADRENALINE', meaning: 'A hormone released during excitement or stress' },
  { word: 'ANTIQUITY', meaning: 'The distant past, especially ancient times' },
  { word: 'BARRICADE', meaning: 'A barrier blocking passage' },
  { word: 'CRESCENDO', meaning: 'A gradual increase in loudness or intensity' },
  { word: 'DIMENSION', meaning: 'A measurement of length, width, or height' },
  { word: 'ELECTRODE', meaning: 'A conductor through which electricity enters or leaves' },
  { word: 'FORTITUDE', meaning: 'Courage in the face of pain or adversity' },
  { word: 'GESTATION', meaning: 'The development period before birth' },
  { word: 'HYPNOTIZE', meaning: 'To put someone in a trance-like state' },
  { word: 'INGENIOUS', meaning: 'Cleverly inventive or resourceful' },
  { word: 'JUXTAPOSE', meaning: 'To place two things side by side for comparison' },
  { word: 'KILOMETER', meaning: 'A unit of distance equal to 1000 meters' },
  { word: 'LONGITUDE', meaning: 'The east-west position on Earth\'s surface' },
  { word: 'MIGRATION', meaning: 'Movement from one region to another' },
  { word: 'PENINSULA', meaning: 'A piece of land mostly surrounded by water' },
  { word: 'PREDATORY', meaning: 'Hunting and killing other animals for food' },
  { word: 'QUICKSAND', meaning: 'Loose wet sand that sucks in anything on top' },
  { word: 'RENEWABLE', meaning: 'Able to be replaced naturally over time' },
  { word: 'SOVEREIGN', meaning: 'Having supreme power or authority' },
  { word: 'THRESHOLD', meaning: 'The point at which something begins' },
  { word: 'UNDERTOW', meaning: 'A current below the surface pulling away from shore' },
  { word: 'VENTILATE', meaning: 'To allow fresh air to circulate in a space' },
  { word: 'WANDERING', meaning: 'Traveling without a fixed route' },
  { word: 'YELLOWING', meaning: 'Becoming yellow with age' },
  { word: 'BEGINNING', meaning: 'The start or first part of something' },
  { word: 'CAPTIVATE', meaning: 'To attract and hold attention' },
  { word: 'DIAPHRAGM', meaning: 'A muscle below the lungs used for breathing' },
  { word: 'ENCOMPASS', meaning: 'To surround or include completely' },
  { word: 'FABRICATE', meaning: 'To construct or manufacture something' },
  { word: 'HARMONIZE', meaning: 'To bring into agreement or pleasing arrangement' },
  { word: 'IRIDESCENT', meaning: 'Showing rainbow-like colors that shift' },
  { word: 'MYTHOLOGY', meaning: 'A collection of myths belonging to a culture' },

  // === 10-letter words (30) ===
  { word: 'REVOLUTION', meaning: 'A dramatic and wide-reaching change' },
  { word: 'EARTHQUAKE', meaning: 'A sudden shaking of the ground' },
  { word: 'WILDERNESS', meaning: 'A wild and uninhabited natural area' },
  { word: 'BLACKSMITH', meaning: 'A person who makes things from iron' },
  { word: 'ECOSYSTEM', meaning: 'A community of living things interacting with their environment' },
  { word: 'EXPERIMENT', meaning: 'A scientific test to discover something new' },
  { word: 'HYPOTHESIS', meaning: 'An educated guess that can be tested' },
  { word: 'NAVIGATION', meaning: 'The process of finding your way' },
  { word: 'PHENOMENON', meaning: 'An extraordinary event or occurrence' },
  { word: 'WAVELENGTH', meaning: 'The distance between peaks of a wave' },
  { word: 'COMBUSTION', meaning: 'The process of burning' },
  { word: 'HEMISPHERE', meaning: 'Half of a sphere, especially Earth' },
  { word: 'MANUSCRIPT', meaning: 'A handwritten or typed text' },
  { word: 'OSCILLATION', meaning: 'Regular back-and-forth movement' },
  { word: 'PLANTATION', meaning: 'A large estate where crops are grown' },
  { word: 'REFRACTION', meaning: 'The bending of light as it passes through' },
  { word: 'SPACECRAFT', meaning: 'A vehicle for traveling in space' },
  { word: 'GENERATION', meaning: 'All people born around the same time' },
  { word: 'CHRONOLOGY', meaning: 'The arrangement of events in time order' },
  { word: 'LITERATURE', meaning: 'Written works regarded as having artistic merit' },
  { word: 'MICROSCOPE', meaning: 'A device for seeing very small things' },
  { word: 'REVOLUTION', meaning: 'A complete orbit or a dramatic change' },
  { word: 'SUSPENSION', meaning: 'The state of being hung or temporarily stopped' },
  { word: 'TURBULENCE', meaning: 'Violent or unsteady movement of air or water' },
  { word: 'AMPHIBIOUS', meaning: 'Able to live both on land and in water' },
  { word: 'BINOCULARS', meaning: 'A device with two lenses for seeing distant objects' },
  { word: 'CENTRIFUGE', meaning: 'A machine that spins rapidly to separate substances' },
  { word: 'PETRIFYING', meaning: 'So frightening as to cause inability to move' },
  { word: 'QUARANTINE', meaning: 'Isolation to prevent the spread of disease' },
  { word: 'TABLESPOON', meaning: 'A large spoon used for measuring' },

  // === 11-letter words (20) ===
  { word: 'CONSTELLATION', meaning: 'A group of stars forming a pattern' },
  { word: 'TEMPERATURE', meaning: 'How hot or cold something is' },
  { word: 'ARCHIPELAGO', meaning: 'A group of islands' },
  { word: 'DESTRUCTION', meaning: 'The act of destroying something completely' },
  { word: 'EXPLORATION', meaning: 'Traveling to discover new places' },
  { word: 'INDEPENDENT', meaning: 'Free from outside control' },
  { word: 'THUNDERBOLT', meaning: 'A flash of lightning with thunder' },
  { word: 'CARNIVOROUS', meaning: 'An animal that eats meat' },
  { word: 'ELECTRICITY', meaning: 'A form of energy from charged particles' },
  { word: 'ACKNOWLEDGE', meaning: 'To accept or recognize something as true' },
  { word: 'EVAPORATION', meaning: 'When liquid turns into gas' },
  { word: 'GERMINATION', meaning: 'When a seed begins to sprout and grow' },
  { word: 'HIBERNATION', meaning: 'A deep sleep animals enter to survive winter' },
  { word: 'IMAGINATION', meaning: 'The ability to form new ideas and images' },
  { word: 'EQUILIBRIUM', meaning: 'A state of balance between opposing forces' },
  { word: 'FURTHERMORE', meaning: 'In addition to what has been said' },
  { word: 'COLLABORATE', meaning: 'To work together on a project' },
  { word: 'DISTINGUISH', meaning: 'To recognize or tell the difference' },
  { word: 'CATASTROPHE', meaning: 'A sudden disaster causing great damage' },
  { word: 'RADIOACTIVE', meaning: 'Emitting harmful radiation' },

  // === 12+ letter words (10) ===
  { word: 'PHOTOSYNTHESIS', meaning: 'The process plants use to convert sunlight into food' },
  { word: 'EXTRAORDINARY', meaning: 'Very unusual or remarkably great' },
  { word: 'CIRCUMFERENCE', meaning: 'The distance around the edge of a circle' },
  { word: 'PRECIPITATION', meaning: 'Water falling from clouds as rain, snow, or hail' },
  { word: 'ARCHAEOLOGICAL', meaning: 'Related to the study of ancient history through objects' },
  { word: 'METAMORPHOSIS', meaning: 'A complete change in form' },
  { word: 'INDEPENDENCE', meaning: 'Freedom from the control of others' },
  { word: 'BIODIVERSITY', meaning: 'The variety of life in an environment' },
  { word: 'COMMUNICATION', meaning: 'The exchange of information between people' },
  { word: 'GRAVITATIONAL', meaning: 'Relating to the force of gravity' },
];
