export const WORD_DB = {
  1: [
    { word: 'SUN', meaning: 'The star at the center of our solar system that gives us light and heat' },
    { word: 'BIG', meaning: 'Large in size, amount, or degree' },
    { word: 'RUN', meaning: 'To move quickly using your legs, faster than walking' },
    { word: 'CAT', meaning: 'A small furry animal often kept as a pet' },
    { word: 'MAP', meaning: 'A drawing that shows where places are' },
    { word: 'HOP', meaning: 'To jump on one foot or make short jumps' },
    { word: 'CUP', meaning: 'A small container used for drinking' },
    { word: 'RED', meaning: 'The color of fire trucks and ripe tomatoes' },
    { word: 'DOG', meaning: 'A friendly animal often kept as a pet that barks' },
    { word: 'FIN', meaning: 'The flat part on a fish that helps it swim' },
  ],
  2: [
    { word: 'BRAVE', meaning: 'Ready to face danger or pain without showing fear' },
    { word: 'CLIMB', meaning: 'To go up something using your hands and feet' },
    { word: 'FLOAT', meaning: 'To stay on the surface of a liquid without sinking' },
    { word: 'PROUD', meaning: 'Feeling happy about something you or someone else has done' },
    { word: 'SHINY', meaning: 'Bright and reflecting light' },
    { word: 'STORM', meaning: 'Very bad weather with strong winds, rain, and sometimes lightning' },
    { word: 'GRASP', meaning: 'To take hold of something firmly' },
    { word: 'BLOOM', meaning: 'When a flower opens up its petals' },
    { word: 'CREEK', meaning: 'A small narrow stream of water' },
    { word: 'SWIFT', meaning: 'Moving or able to move very quickly' },
  ],
  3: [
    { word: 'ORBIT', meaning: 'The curved path a planet follows around a star' },
    { word: 'LUNAR', meaning: 'Relating to the moon' },
    { word: 'COMET', meaning: 'A bright object in space with a long tail made of ice and dust' },
    { word: 'QUEST', meaning: 'A long search for something important' },
    { word: 'SOLAR', meaning: 'Relating to the sun' },
    { word: 'FROST', meaning: 'A thin layer of ice that forms on cold surfaces' },
    { word: 'BLAZE', meaning: 'A large strong fire that burns brightly' },
    { word: 'GLOBE', meaning: 'A round model of the Earth or the Earth itself' },
    { word: 'SWIFT', meaning: 'Moving or capable of moving at high speed' },
    { word: 'CRANE', meaning: 'A large tall machine used to lift heavy things or a large bird with long legs' },
  ],
  4: [
    { word: 'GRAVITY', meaning: 'The force that pulls objects toward each other and keeps us on the ground' },
    { word: 'ANCIENT', meaning: 'Belonging to a time long ago in history' },
    { word: 'JOURNEY', meaning: 'A long trip from one place to another' },
    { word: 'IMAGINE', meaning: 'To create pictures or ideas in your mind' },
    { word: 'MYSTERY', meaning: 'Something that is difficult to understand or explain' },
    { word: 'BALANCE', meaning: 'Being steady and not falling to one side' },
    { word: 'HARVEST', meaning: 'The time when crops are gathered from the fields' },
    { word: 'COURAGE', meaning: 'The ability to do something that frightens you' },
    { word: 'COMPETE', meaning: 'To try to win or do better than others' },
    { word: 'SHELTER', meaning: 'A place that protects you from bad weather or danger' },
  ],
  5: [
    { word: 'ATMOSPHERE', meaning: 'The layer of gases surrounding a planet' },
    { word: 'TELESCOPE', meaning: 'An instrument used to see distant objects in space' },
    { word: 'BRILLIANT', meaning: 'Extremely clever or bright and shining' },
    { word: 'COMMUNITY', meaning: 'A group of people living in the same area or sharing interests' },
    { word: 'DANGEROUS', meaning: 'Able to cause harm or injury to someone' },
    { word: 'ELABORATE', meaning: 'Very detailed and carefully planned' },
    { word: 'FREQUENCY', meaning: 'How often something happens in a given time period' },
    { word: 'NEGOTIATE', meaning: 'To discuss something in order to reach an agreement' },
    { word: 'PENINSULA', meaning: 'A piece of land almost surrounded by water on three sides' },
    { word: 'NARRATIVE', meaning: 'A spoken or written account of connected events, a story' },
  ],
  6: [
    { word: 'CONSTELLATION', meaning: 'A group of stars that form a pattern in the night sky' },
    { word: 'PHOTOSYNTHESIS', meaning: 'The process plants use to convert sunlight into food' },
    { word: 'EXTRAORDINARY', meaning: 'Very unusual or remarkably great' },
    { word: 'CIRCUMFERENCE', meaning: 'The distance around the edge of a circle' },
    { word: 'PRECIPITATION', meaning: 'Water that falls from clouds as rain, snow, or hail' },
    { word: 'REVOLUTIONARY', meaning: 'Involving a great or complete change' },
    { word: 'ARCHAEOLOGICAL', meaning: 'Related to the study of ancient human history through objects' },
    { word: 'METAMORPHOSIS', meaning: 'A complete change in form, like a caterpillar becoming a butterfly' },
    { word: 'INDEPENDENCE', meaning: 'The state of being free from the control of others' },
    { word: 'BIODIVERSITY', meaning: 'The variety of different plants and animals in an environment' },
  ],
};
